name: share_launcher
description: A launcher that handles share functionality on a device.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  share_plus: ^6.0.1
  share_plus_platform_interface: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.2
  url_launcher_platform_interface: ^2.0.5
  very_good_analysis: ^4.0.0
