version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/api/packages/news_blocks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/permission_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/app_ui/gallery"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/app_ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_client/authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_client/firebase_authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_client/token_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/news_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/share_launcher"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/form_inputs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/storage/storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/storage/secure_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/storage/persistent_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ads_consent_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/in_app_purchase_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/article_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/package_info_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/email_launcher"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/user_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/purchase_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/deep_link_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/notifications_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/analytics_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/news_blocks_ui"
    schedule:
      interval: "daily"
