name: token_storage
description: Token storage for the authentication client.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^1.0.2
  test: ^1.21.4
  very_good_analysis: ^6.0.0
