name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  formz: ^0.6.0

dev_dependencies:
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
