version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: 'daily'
  - package-ecosystem: "pub"
    directory: "/tool/generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/api/packages/news_blocks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/permission_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/app_ui/gallery"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/app_ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/authentication_client/authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/authentication_client/firebase_authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/authentication_client/token_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/news_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/share_launcher"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/form_inputs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/storage/storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/storage/secure_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/storage/persistent_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/ads_consent_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/in_app_purchase_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/article_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/package_info_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/email_launcher"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/user_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/purchase_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/deep_link_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/notifications_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/analytics_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_news_example/packages/news_blocks_ui"
    schedule:
      interval: "daily"
