name: secure_storage
description: A Key/Value Secure Storage Client
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.0.0
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
