name: firebase_notifications_client
description: A Firebase Cloud Messaging notifications client.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  firebase_messaging: ^12.0.1
  flutter:
    sdk: flutter
  notifications_client:
    path: ../notifications_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
