name: {{project_name.snakeCase()}}_api
description: A {{app_name}} server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  dart_frog: ^1.0.1
  equatable: ^2.0.5
  http: ^1.0.0
  json_annotation: ^4.6.0
  news_blocks:
    path: packages/news_blocks

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  test: ^1.24.9
  very_good_analysis: ^5.1.0
