name: flutter_news_example
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.6"
dependencies:
  ads_consent_client:
    path: packages/ads_consent_client
  analytics_repository:
    path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  article_repository:
    path: packages/article_repository
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  clock: ^1.1.0
  collection: ^1.16.0
  deep_link_client:
    path: packages/deep_link_client
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.3
  firebase_analytics: ^10.0.3
  firebase_auth_platform_interface: ^6.11.0
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  firebase_dynamic_links: ^5.0.3
  firebase_messaging: ^14.0.3
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  flow_builder: ^0.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_news_example_api:
    path: api
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  google_mobile_ads: ^3.1.0
  hydrated_bloc: ^9.0.0
  in_app_purchase_repository:
    path: packages/in_app_purchase_repository
  intl: ^0.18.0
  json_annotation: ^4.7.0
  mockingjay: ^0.4.0
  news_blocks:
    path: api/packages/news_blocks
  news_blocks_ui:
    path: packages/news_blocks_ui
  news_repository:
    path: packages/news_repository
  notifications_repository:
    path: packages/notifications_repository
  package_info_client:
    path: packages/package_info_client
  path_provider: ^2.0.2
  permission_client:
    path: packages/permission_client
  persistent_storage:
    path: packages/storage/persistent_storage
  platform: ^3.0.2
  purchase_client:
    path: packages/purchase_client
  share_launcher:
    path: packages/share_launcher
  shared_preferences: ^2.0.15
  sliver_tools: ^0.2.9
  stream_transform: ^2.0.0
  test: ^1.21.4
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.0.9
  user_repository:
    path: packages/user_repository
  very_good_analysis: ^5.1.0
  video_player_platform_interface: ^6.0.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.3
  build_verify: ^3.0.0
  build_version: ^2.0.3
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:
  generate: true
  uses-material-design: true
