name: gallery
description: Gallery project to showcase app_ui
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  app_ui:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
