name: share_launcher
description: A launcher that handles share functionality on a device.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  share_plus: ^10.0.2
  share_plus_platform_interface: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  plugin_platform_interface: ^2.1.2
  url_launcher_platform_interface: ^2.0.5
  very_good_analysis: ^6.0.0
