name: news_blocks
description: Reusable News Blocks for the {{app_name}} Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.1.0
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.0
