name: news_blocks_ui
description: A Flutter package that contains UI components for news blocks.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  app_ui:
    path: ../app_ui
  flutter:
    sdk: flutter
  news_blocks:
    path: ../../api/packages/news_blocks

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
flutter:
  uses-material-design: true
