name: in_app_purchase_repository
description: A repository that manages user purchase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_news_template_api:
    path: ../../api
  in_app_purchase: ^3.0.5
  rxdart: ^0.27.4

dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0
