name: notifications_repository
description: A repository that manages notification permissions and topic subscriptions.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_news_example_api:
    path: ../../api
  notifications_client:
    path: ../notifications_client/notifications_client
  permission_client:
    path: ../permission_client
  storage:
    path: ../storage/storage
  test: ^1.21.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
