name: notifications_repository
description: A repository that manages notification permissions and topic subscriptions.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_news_template_api:
    path: ../../api
  notifications_client:
    path: ../notifications_client/notifications_client
  permission_client:
    path: ../permission_client
  storage:
    path: ../storage/storage
  test: ^1.21.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
