name: firebase_authentication_client
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^4.1.0
  firebase_auth_platform_interface: ^6.11.0
  firebase_core: ^2.1.1
  firebase_core_platform_interface: ^4.5.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.8
  google_sign_in: ^6.0.2
  plugin_platform_interface: ^2.1.3
  sign_in_with_apple: ^4.1.0
  token_storage:
    path: ../token_storage
  twitter_login: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
