name: purchase_client
description: A PurchaseClient stubbing InAppPurchase implementation.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_news_template_api:
    path: ../../api
  in_app_purchase: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
