name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  deep_link_client:
    path: ../deep_link_client
  equatable: ^2.0.3
  flutter_news_example_api:
    path: ../../api
  package_info_client:
    path: ../package_info_client
  rxdart: ^0.27.5
  storage:
    path: ../storage/storage

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^5.1.0
