name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  deep_link_client:
    path: ../deep_link_client
  equatable: ^2.0.3
  flutter_news_template_api:
    path: ../../api
  package_info_client:
    path: ../package_info_client
  rxdart: ^0.27.5
  storage:
    path: ../storage/storage

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.0
