name: flutter_news_example_api
description: A Flutter News Example server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  dart_frog: ^1.1.0
  equatable: ^2.0.7
  http: ^1.2.2
  json_annotation: ^4.9.0
  news_blocks:
    path: packages/news_blocks

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0

dependency_overrides:
  frontend_server_client: ^4.0.0