name: flutter_news_template_api
description: A Flutter News Toolkit server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  dart_frog: ^0.2.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.6.0
  news_blocks:
    path: packages/news_blocks

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.1.0
