name: firebase_authentication_client
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^3.0.1  
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.5
  sign_in_with_apple: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
  