name: deep_link_client
description: A Dart package which provides a deep link stream
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_core: ^3.0.0
  firebase_dynamic_links: ^6.0.0
  plugin_platform_interface: ^2.1.3
  rxdart: ^0.27.3

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
