name: token_storage
description: Token storage for the authentication client.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^4.0.0
