name: article_repository

concurrency:
  group: ${{#mustacheCase}}github.workflow{{/mustacheCase}}-${{#mustacheCase}}github.ref{{/mustacheCase}}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/article_repository/**"
      - ".github/workflows/article_repository.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.0.2
      working_directory: packages/article_repository
