name: news_blocks_ui

concurrency:
  group: ${{#mustacheCase}}github.workflow{{/mustacheCase}}-${{#mustacheCase}}github.ref{{/mustacheCase}}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/news_blocks_ui/**"
      - ".github/workflows/news_blocks_ui.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: {{flutter_version}}
      working_directory: packages/news_blocks_ui
      coverage_excludes: "lib/src/generated/*.dart"
