name: token_storage

concurrency:
  group: ${{#mustacheCase}}github.workflow{{/mustacheCase}}-${{#mustacheCase}}github.ref{{/mustacheCase}}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/authentication_client/token_storage/**"
      - ".github/workflows/token_storage.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 2.19.3
      working_directory: packages/authentication_client/token_storage
