name: analytics_repository
description: Package which manages the analytics domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_analytics: ^10.4.3
  flutter:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
