name: analytics_repository
description: Package which manages the analytics domain.
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  firebase_analytics: ^10.0.3
  flutter:
    sdk: flutter
  very_good_analysis: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
