name: email_launcher
description: A package to open an external email app on Android and iOS
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  android_intent_plus: ^5.0.1
  flutter:
    sdk: flutter
  platform: ^3.0.2
  plugin_platform_interface: ^2.1.3
  url_launcher: ^6.1.5
  url_launcher_platform_interface: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
