name: article_repository
description: A repository that manages article data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  equatable: ^2.0.3
  flutter_news_template_api:
    path: ../../api
  storage:
    path: ../storage/storage

dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0
