name: article_repository
description: A repository that manages article data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.0
  equatable: ^2.0.3
  flutter_news_example_api:
    path: ../../api
  storage:
    path: ../storage/storage

dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^5.1.0
