name: firebase_authentication_client
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^5.2.1
  firebase_auth_platform_interface: ^7.4.5
  firebase_core: ^3.4.1
  firebase_core_platform_interface: ^5.2.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.1
  plugin_platform_interface: ^2.1.3
  sign_in_with_apple: ^6.1.0
  token_storage:
    path: ../token_storage
  twitter_login: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
